#!/usr/bin/env python3
"""Google Search Console setup helper for Seller Tools."""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
CONFIG = ROOT / "pipeline" / "gsc.json"
GSC_CONFIG_JS = SITE / "assets" / "gsc-config.js"

HTML_PAGES = [
    SITE / "index.html",
    SITE / "listing-lab" / "index.html",
    SITE / "etsy-tag-finder" / "index.html",
    *sorted((SITE / "guides").glob("*.html")),
]

META_SNIPPET = '  <meta name="google-site-verification" content="{token}" />'


def load_config() -> dict:
    if CONFIG.exists():
        return json.loads(CONFIG.read_text())
    return {
        "site_url": "",
        "verification": {"method": None, "token": None, "verified": False},
        "sitemap": {"url": "", "submitted": False},
        "created_at": None,
        "updated_at": None,
    }


def save_config(cfg: dict) -> None:
    cfg["updated_at"] = datetime.now(timezone.utc).isoformat()
    if not cfg.get("created_at"):
        cfg["created_at"] = cfg["updated_at"]
    CONFIG.parent.mkdir(parents=True, exist_ok=True)
    CONFIG.write_text(json.dumps(cfg, indent=2) + "\n")


def normalize_url(url: str) -> str:
    url = url.strip().rstrip("/")
    if not url.startswith("http"):
        raise ValueError("Site URL must start with http:// or https://")
    return url


def write_gsc_config_js(token: str | None) -> None:
    if token:
        content = f'// Auto-generated by gsc_setup.py — do not edit\nwindow.GSC_VERIFICATION = "{token}";\n'
    else:
        content = "// Run: python3 scripts/gsc_setup.py set-token YOUR_TOKEN\nwindow.GSC_VERIFICATION = null;\n"
    GSC_CONFIG_JS.write_text(content)


def write_html_file_verification(filename: str) -> Path:
    path = SITE / filename
    path.write_text(f"google-site-verification: {filename}\n")
    return path


def inject_meta_tag(token: str) -> int:
    meta = META_SNIPPET.format(token=token)
    meta_re = re.compile(
        r'\s*<meta name="google-site-verification" content="[^"]*" />\n?',
        re.IGNORECASE,
    )
    updated = 0
    for page in HTML_PAGES:
        if not page.exists():
            continue
        text = page.read_text()
        if meta_re.search(text):
            text = meta_re.sub("\n" + meta + "\n", text, count=1)
        elif "<head>" in text:
            text = text.replace("<head>", "<head>\n" + meta, 1)
        else:
            continue
        page.write_text(text)
        updated += 1
    return updated


def remove_meta_tag() -> None:
    meta_re = re.compile(
        r'\s*<meta name="google-site-verification" content="[^"]*" />\n?',
        re.IGNORECASE,
    )
    for page in HTML_PAGES:
        if page.exists():
            page.write_text(meta_re.sub("", page.read_text()))


def cmd_init(args: argparse.Namespace) -> None:
    base = normalize_url(args.url)
    cfg = load_config()
    cfg["site_url"] = base
    cfg["sitemap"]["url"] = f"{base}/sitemap.xml"
    save_config(cfg)

    import subprocess

    subprocess.run(
        [sys.executable, str(ROOT / "scripts" / "build_sitemap.py"), "--base", base],
        check=True,
    )
    write_gsc_config_js(None)

    print("GSC config initialized.")
    print(f"  Site URL:    {base}")
    print(f"  Sitemap:     {cfg['sitemap']['url']}")
    print()
    print_next_steps(base)


def cmd_set_token(args: argparse.Namespace) -> None:
    token = args.token.strip()
    if not token:
        raise SystemExit("Token cannot be empty")

    cfg = load_config()
    cfg["verification"]["method"] = "meta"
    cfg["verification"]["token"] = token
    cfg["verification"]["verified"] = False
    save_config(cfg)

    write_gsc_config_js(token)
    count = inject_meta_tag(token)
    print(f"Injected verification meta tag into {count} pages.")
    print(f"Wrote {GSC_CONFIG_JS}")
    print()
    print("Next: deploy site, then click Verify in Search Console.")


def cmd_set_html_file(args: argparse.Namespace) -> None:
    filename = args.filename.strip()
    if not filename.startswith("google") or not filename.endswith(".html"):
        raise SystemExit("Filename must look like googleXXXXXXXX.html")

    cfg = load_config()
    cfg["verification"]["method"] = "html_file"
    cfg["verification"]["token"] = filename
    cfg["verification"]["verified"] = False
    save_config(cfg)

    path = write_html_file_verification(filename)
    print(f"Created verification file: {path}")
    print("Deploy site, then click Verify in Search Console.")


def cmd_mark_verified(args: argparse.Namespace) -> None:
    cfg = load_config()
    cfg["verification"]["verified"] = True
    if args.sitemap_submitted:
        cfg["sitemap"]["submitted"] = True
    save_config(cfg)
    print("Marked as verified in pipeline/gsc.json")
    if cfg.get("site_url"):
        print(f"Submit sitemap manually: {cfg['sitemap']['url']}")


def cmd_status(_: argparse.Namespace) -> None:
    cfg = load_config()
    print("Google Search Console — Seller Tools")
    print("=" * 44)
    print(f"Site URL:      {cfg.get('site_url') or '(not set — run init)'}")
    v = cfg.get("verification", {})
    print(f"Verification:  {v.get('method') or 'pending'}")
    print(f"Token/file:    {v.get('token') or '—'}")
    print(f"Verified:      {v.get('verified', False)}")
    s = cfg.get("sitemap", {})
    print(f"Sitemap URL:   {s.get('url') or '—'}")
    print(f"Sitemap sent:  {s.get('submitted', False)}")
    print()
    if cfg.get("site_url") and not v.get("verified"):
        print_next_steps(cfg["site_url"])


def print_next_steps(base: str) -> None:
    print("─── Google Search Console steps ───")
    print()
    print("1. Open https://search.google.com/search-console")
    print("2. Add property → URL prefix")
    print(f"   {base}/")
    print("3. Choose verification method:")
    print()
    print("   META TAG (recommended):")
    print("   - Google shows: <meta name=\"google-site-verification\" content=\"TOKEN\" />")
    print("   - Run: python3 scripts/gsc_setup.py set-token TOKEN")
    print("   - Deploy site → click Verify in GSC")
    print()
    print("   HTML FILE (alternative):")
    print("   - Google gives filename e.g. googleabc123.html")
    print("   - Run: python3 scripts/gsc_setup.py set-html-file googleabc123.html")
    print("   - Deploy → Verify")
    print()
    print("4. After verified → Sitemaps → Submit:")
    print(f"   sitemap.xml  (full URL: {base}/sitemap.xml)")
    print()
    print("5. Request indexing for key pages:")
    print(f"   {base}/")
    print(f"   {base}/listing-lab/")
    print(f"   {base}/etsy-tag-finder/")
    print(f"   {base}/guides/how-to-choose-etsy-tags.html")


def main() -> None:
    parser = argparse.ArgumentParser(description="Google Search Console setup")
    sub = parser.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="Set site URL and rebuild sitemap")
    p_init.add_argument("--url", required=True, help="Live site base URL")
    p_init.set_defaults(func=cmd_init)

    p_token = sub.add_parser("set-token", help="Add HTML meta verification tag")
    p_token.add_argument("token", help="content= value from Google")
    p_token.set_defaults(func=cmd_set_token)

    p_html = sub.add_parser("set-html-file", help="Create google*.html verification file")
    p_html.add_argument("filename", help="e.g. googleabc123.html")
    p_html.set_defaults(func=cmd_set_html_file)

    p_done = sub.add_parser("mark-verified", help="Record successful verification")
    p_done.add_argument("--sitemap-submitted", action="store_true")
    p_done.set_defaults(func=cmd_mark_verified)

    p_status = sub.add_parser("status", help="Show GSC setup status")
    p_status.set_defaults(func=cmd_status)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()